### basic settings

# site properties and page defaults
title: Sensation in Motion Lab
subtitle: At San Diego State University
description: Sensation in Motion Lab at San Diego State University. We study sensory structures and motor functions underlying everyday hand use. 
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: sreschechtko@sdsu.edu
  google-scholar: Sasha Reschechtko
  # github: your-lab

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
