- id: doi:10.1016/j.cub.2020.07.092
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982220311519-gr2.jpg
  #date: 2020-6-2
  #extra-links:
  #  - type: manubot
  #    link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - Review
    - Reflexes

- id: doi:10.1152/jn.00232.2020
  image: https://journals.physiology.org/cms/10.1152/jn.00232.2020/asset/images/medium/z9k0072055220001.gif
  tags:
    - Cutaneous
    - Reflexes
    - Fingers
    - Upper Limb
  #repo: greenelab/meta-review
  #extra-links:
  #  - type: manubot
  #    link: https://greenelab.github.io/meta-review/
  #  - type: source
  #    link: https://github.com/greenelab/meta-review
  #  - type: website
  #    link: http://manubot.org/

- id: doi:10.1016/j.cophys.2021.02.001
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2468867321000328-gr1.jpg
  tags:
    - Cutaneous
    - Reflexes
    - Review
    
- id: doi:10.1111/ejn.14479
  image: https://onlinelibrary.wiley.com/cms/asset/ec7ff9c3-c024-434b-9f2d-d0375463df42/ejn14479-fig-0001-m.png
  tags:
    - Reflexes
    - Perturbation
    - Upper Limb
    
- id: doi:10.1007/s00221-019-05709-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-019-05709-6/MediaObjects/221_2019_5709_Fig1_HTML.png
  tags:
    - Parkinsons Disease
    - Fingers
    - Coordination
    - Perturbation

- id: doi:10.1080/00222895.2019.1580670
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/vjmb20.v052.i01
  tags:
    - Fingers
    - Anesthesia
    - Cutaneous
    
- id: doi:10.1371/journal.pone.0226596
  image: https://journals.plos.org/plosone/article/figure/image?size=large&id=10.1371/journal.pone.0226596.g001
  tags:
    - Fingers
    - Anesthesia
    - Cutaneous
    - Coordination
    
- id: doi:10.1007/s00221-018-5231-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-018-5231-5/MediaObjects/221_2018_5231_Fig1_HTML.gif
  tags:
    - Fingers
    - Variability
    - Coordination

- id: doi:10.1523/JNEUROSCI.3224-17.2018
  image: https://www.jneurosci.org/sites/default/files/styles/medium/public/highwire/jneuro/38/10.cover-source.jpg
  tags:
    - Review
    - Variability

- id: doi:10.1007/s00221-018-5231-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-018-5179-5/MediaObjects/221_2018_5179_Fig7_HTML.gif
  tags:
    - Cooperation
    - Fingers
    - Cyclical
    
- id: doi:10.1152/jn.00485.2017
  image: https://journals.physiology.org/cms/10.1152/jn.00485.2017/asset/images/medium/z9k0111743900001.gif
  tags:
    - Perturbation
    - Fingers
    - Coordination
