- id: doi:10.1101/2022.12.24.521682
  image: images/jump_move.png
  tags:
    - Upper Limb
    - Reflexes
  extra-links:
    - type: preprint
    - link: https://doi.org/10.1101/2022.12.24.521682

- id: doi:10.1016/j.cub.2020.07.092
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982220311519-gr2.jpg
  tags:
    - Review
    - Reflexes

- id: doi:10.1152/jn.00232.2020
  image: https://journals.physiology.org/cms/10.1152/jn.00232.2020/asset/images/medium/z9k0072055220001.gif
  tags:
    - Cutaneous
    - Reflexes
    - Fingers
    - Upper Limb
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2020.04.01.020529v1
  
- id: doi:10.1016/j.cophys.2021.02.001
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2468867321000328-gr1.jpg
  tags:
    - Cutaneous
    - Reflexes
    - Review
    
- id: doi:10.1111/ejn.14479
  image: https://onlinelibrary.wiley.com/cms/asset/ec7ff9c3-c024-434b-9f2d-d0375463df42/ejn14479-fig-0001-m.png
  tags:
    - Reflexes
    - Perturbation
    - Upper Limb
  extra-links:
    - type: preprint
      link: https://doi.org/10.1101/578450
    
- id: doi:10.1007/s00221-019-05709-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-019-05709-6/MediaObjects/221_2019_5709_Fig1_HTML.png
  tags:
    - Parkinsons Disease
    - Fingers
    - Coordination
    - Perturbation

- id: doi:10.1080/00222895.2019.1580670
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/vjmb20.v052.i01
  tags:
    - Fingers
    - Anesthesia
    - Cutaneous
    - Carpal Tunnel
    
- id: doi:10.1371/journal.pone.0226596
  image: https://journals.plos.org/plosone/article/figure/image?size=large&id=10.1371/journal.pone.0226596.g001
  tags:
    - Fingers
    - Anesthesia
    - Cutaneous
    - Coordination
    - Carpal Tunnel
    
- id: doi:10.1152/jn.00045.2018
  image: https://journals.physiology.org/cms/10.1152/jn.00045.2018/asset/images/medium/z9k0081847070001.gif
  tags:
    - Fingers
    - Variability
    - Perturbation
    - Coordination
    
- id: doi:10.1007/s00221-018-5231-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-018-5231-5/MediaObjects/221_2018_5231_Fig1_HTML.gif
  tags:
    - Fingers
    - Variability
    - Coordination

- id: doi:10.1523/JNEUROSCI.3224-17.2018
  image: https://www.jneurosci.org/sites/default/files/styles/medium/public/highwire/jneuro/38/10.cover-source.jpg
  tags:
    - Review
    - Variability

- id: doi:10.1007/s00221-018-5179-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-018-5179-5/MediaObjects/221_2018_5179_Fig7_HTML.gif
  tags:
    - Two-Person Cooperation
    - Fingers
    - Cyclical
    
- id: doi:10.1152/jn.00485.2017
  image: https://journals.physiology.org/cms/10.1152/jn.00485.2017/asset/images/medium/z9k0111743900001.gif
  tags:
    - Perturbation
    - Fingers
    - Coordination

- id: doi:10.1152/jn.00563.2017
  image: https://journals.physiology.org/cms/10.1152/jn.00563.2017/asset/images/medium/z9k0121744210006.gif
  tags:
    - Fingers
    - Illusion
    - Vibration
    
- id: doi:10.1016/j.neuroscience.2017.03.022
  image: https://ars.els-cdn.com/content/image/1-s2.0-S030645221730180X-gr3.jpg
  tags:
    - Fingers
    - Cyclical

- id: doi:10.1007/s00221-016-4768-4
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-016-4768-4/MediaObjects/221_2016_4768_Fig1_HTML.gif
  tags:
    - Fingers
    - Tangential Force
    - Variability

- id: doi:10.1016/j.clinbiomech.2017.06.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0268003317301316-gr1.jpg
  tags:
    - Fall Prevention
    - Slipping
    - Lower Limb

- id: doi:10.1007/s00221-016-4632-6
  image: https://link.springer.com/article/10.1007/s00221-016-4632-6/figures/1
  tags:
    - Two-Person Cooperation
    - Variability
    - Prehension
 
- id: doi:10.1007/s00221-015-4364-z
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00221-015-4364-z/MediaObjects/221_2015_4364_Fig1_HTML.gif
  tags:
    - Two-Person Cooperation
    - Variability
    - Fingers
    
- id: doi:10.1080/00222895.2014.996281
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4710373/bin/nihms749294f2.jpg
  tags:
    - Fingers
    - Variability
    - Perturbation
    
- id: doi:10.1152/jn.00395.2014
  image: https://journals.physiology.org/na101/home/literatum/publisher/physio/journals/content/jn/2014/jn.2014.112.issue-12/jn.2014.112.issue-12/20180103-01/jn.2014.112.issue-12.cover.gif
  tags:
    - Fingers
    - Variability
    - Perturbation
  
- id: doi:10.1101/2022.07.18.500469
  image: https://www.biorxiv.org/sites/default/files/site_logo/bioRxiv_logo_homepage.png
  tags:
    - Preprint
    - Balance
    - Estrogen
    - Menstrual Cycle
  extra-links:
    - type: preprint
      link: https://doi.org/10.1101/2022.07.18.500469
